server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://106.14.147.66:3306/memorandum?serverTimezone=GMT%2B8
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 5
      min-idle: 5
      initial-size: 5
      max-wait-millis: 1000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 1880
    tomcat:
      max-wait: 1000
      max-active: 100
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    generate-ddl: true
  jackson:
    time-zone: GMT+8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
